# Generated by Django 4.0.3 on 2022-04-26 04:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('albumId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pictureId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('isPublished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('password', models.TextField()),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=50)),
                ('albumId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureId', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('fontColor', models.CharField(max_length=100)),
                ('albumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.albums')),
            ],
        ),
    ]
