# Generated by Django 4.0.3 on 2022-04-26 08:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='username',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='webapp.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='albumId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, default=list, size=None),
        ),
    ]
