# Generated by Django 4.0.3 on 2022-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_albums_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
