# Generated by Django 4.0.3 on 2022-04-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_pictures_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='pictureId',
        ),
    ]
